RESOURCE_METHODS = ['GET', 'POST', 'DELETE']
ITEM_METHODS = ['GET', 'PATCH', 'DELETE']
SERVER_NAME = None
MONGO_HOST = 'mongo'
MONGO_PORT = '27017'
MONGO_DBNAME = 'changes'
MOGO_URI = 'mongodb://'+ MONGO_HOST + ':' + MONGO_PORT + '/' + MONGO_DBNAME
